DROP TABLE IF EXISTS records CASCADE;

CREATE TABLE records (
  id SERIAL PRIMARY KEY NOT NULL,
  profit FLOAT NOT NULL,
  stock_option BOOLEAN NOT NULL DEFAULT TRUE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  strategy_id INTEGER REFERENCES strategies(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);