DROP TABLE IF EXISTS strategies CASCADE;

CREATE TABLE strategies (
  id SERIAL PRIMARY KEY NOT NULL,
  strategy_name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  upvotes INTEGER NOT NULL DEFAULT 0,
  downvotes INTEGER NOT NULL DEFAULT 0
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);