DROP TABLE IF EXISTS records CASCADE;

CREATE TABLE records (
  id SERIAL PRIMARY KEY NOT NULL,
  profit FLOAT NOT NULL,
  stock_symbol VARCHAR(255) NOT NULL,
  stock_option BOOLEAN NOT NULL DEFAULT TRUE,
  investment FLOAT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  stock_id INTEGER REFERENCES stocks(id) ON DELETE CASCADE,
  strategy_id INTEGER REFERENCES strategies(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);