INSERT INTO strategies (strategy_name, description, custom) 
VALUES 
('News trading', 'A news trading strategy​​ involves trading based on news and market expectations, both before and following news releases. Trading on news announcements can require a skilled mind-set as news can travel very quickly on digital media. Traders will need to assess the news immediately after it’s released and make a quick judgement on how to trade it.', false),

('Position Trading', 'Position trading uses longer term charts – anywhere from daily to monthly – in combination with other methods to determine the trend of the current market direction. This type of trade may last for several days to several weeks and sometimes longer, depending on the trend. Some actually consider position trading to be a buy-and-hold strategy and not active trading. However, position trading, when done by an advanced trader, can be a form of active trading.', false),

('Swing Trading', 'Swing Trading is a strategy that focuses on taking smaller gains in short term trends and cutting losses quicker. The gains might be smaller, but done consistently over time they can compound into excellent annual returns. Swing Trading positions are usually held a few days to a couple of weeks, but can be held longer. When a trend breaks, swing traders typically get in the game. At the end of a trend, there is usually some price volatility as the new trend tries to establish itself. Swing traders buy or sell as that price volatility sets in. Swing trades are usually held for more than a day but for a shorter time than trend trades. Swing traders often create a set of trading rules based on technical or fundamental analysis.', false),

('Scalping', 'Scalping is one of the quickest strategies employed by active traders. Essentially, it entails identifying and exploiting bid-ask spreads that are a little wider or narrower than normal due to temporary imbalances in supply and demand. A scalper does not attempt to exploit large moves or transact high volumes. Rather, they seek to capitalize on small moves that occur frequently, with measured transaction volumes. Since the level of profit per trade is small, scalpers look for relatively liquid markets to increase the frequency of their trades. Unlike swing traders, scalpers prefer quiet markets that aren''t prone to sudden price movements', false);


INSERT INTO strategies (strategy_name, description, custom, active, upvotes, downvotes) 
VALUES 

('Volume Footprint', 'This indicator estimates a volume footprint using tick data. The script automatically separates a candle into equidistant intervals with a width obtained from the average true range or a user-given width. When applied to a chart, the user will be asked to select the settings to use for the volume footprint. Note that changing the settings afterward will reset the volume footprint, removing previously generated footprints. A new footprint will appear on the confirmation of a new bar, as such this version might only be useful in lower timeframes.', true, true, 10, 4),

('McDonald''s Pattern', 'This script fits a cubic Bezier curve using tops/bottoms in order to approximate a McDonald''s pattern, a popular meme pattern in the crypto trading community. Traditionally the McDonald''s pattern is described by an M pattern with deep retracement (> 50%), forming a McDonald''s logo. The script fits Bezier curves using specific tops/bottoms as control points. When the distance between tops and bottoms values is relatively small, the user can more easily identify the pattern. A score is shown on the top right of the chart, aiming to return how close the returned pattern is to the original logo. A regular Mcdonald''s pattern would return a red background, while an inverted pattern would return a green one.', true, true, 100, 44),

('Wendy''s Strategy', 'Lose all money and go work at Wendy''s', true, true, 0, 99),

('Weighted Strategy', 'The algorithm is based on a combination of well-documented indicators. First, the algorithm calculated the weight_strategy, which represents a value from 0 to 5 of the number of strategies that are fulfilled (in case the weight of each strategy is the same). To open a position, the value of weight_strategy must be greater than the value of weight_signal, by default 2. Modify the indicator parameters for the desired asset and data frame. Set stop-loss and take profit criteria.', true, true, 10, 2),

('AltSession', 'It''s no secret that trading sessions play a massive role in market movement and liquidity. We can clearly see in the image about how important identifying international trading hours are for a trader. The Asian session starts around 1am GMT and often has a bearish bias through this session lasting for a few hours, after which Frankfurt and London traders start to come online and can often reverse the Asian sentiment. The London session is the best session to trade traditionally starting around 7am GMT before the American traders come online and reverse market once again. We have designed this indicator to help identify different trading hours easily with a background shade on the chart and also high/lows of the training session, as these levels can often be revisited.', true, true, 6, 1),

('Range Volume Change', 'RVC visualizes the incremental of the volume using increasing size columns giving you a better view of how the volume changes compared to the past. The column shows the accumulated volume from when the time range started. As an extra feature, it will also show the volume percentage of change outside the time range (can be disabled from settings). In addition, RVC is also designed to work on real-time data.', true, true, 11, 0),

('Buff Averages', 'The Buff Averages were created by Buff Dormeier (Stocks and Commodities Feb 2001) and this is another hidden gem that is a combo of a volume weighted indicator and a moving average crossover system. It uses a special method to calculate the weighting based on volume . The colored line (fast buff) will follow the price closely and you use the other line to act as a trend confirmation. I have included strong buy and sell signals in addition to normal ones so strong signals are darker in color and normal signals are lighter in color. Buy when the line turns green and sell when it turns red.', true, true, 23, 5);
