export const discover = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Discover',
  Headline: 'Find The Right Strategies For You',
  description: 'Share, Follow and Customize Your Strategies',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../../images/biggu.png'),
  primary: true,
  darkText: true,
}

export const manage = {
  id: 'manage',
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Manage',
  Headline: 'Learn About Our App',
  description: 'Keep Track and Get Real-Time Comparison and Analysis of Your Portfolio',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../../images/1st.png'),
  alt: 'Team',
  primary: true,
  darkText: true,
}

export const signup = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'PROMOTION',
  Headline: 'Sign Up Now For 100 Bonus CateCoins',
  description: 'Offer Valid Until 02/28/22 at 11:59pm EST or While Supplies Last. Restrictions May apply.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../../images/img3.png'),
  alt: 'Cat',
  primary: true,
  darkText: true,
}